doc_id: SOP-QC-214
doc_title: "Environmental Monitoring Programme for Aseptic Suites"
doc_type: SOP
version: "3.0"
status: Effective
effective_date: "2026-02-09"
review_due_date: "2028-02-09"
department: "Quality Control Microbiology"
source_file_path: documents/SOP-QC-214-environmental-monitoring-programme-for-aseptic.md
source_hash: sha256:9faba9c6571dd680140c1305d40834af0ec8fa668f9acaaf7a3e8ef66b017a8e
